name: Automatic Changelog from Releases list
on: push
  # release:
  #   types: [created, published]
jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       CURRENTTAG: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
         git config --global user.name 'PyMoBot'
         git config --global user.email 'bot@pymodaq.cnrs.fr'
         git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
         echo "Switching to $CURRENTTAG"
         # echo `git branch --contains tags/$CURRENTTAG |head -n 1`
         git switch `git branch --contains tags/$CURRENTTAG |head -n 1` || git switch $CURRENTTAG
         echo -e "# Changelog\n" > Changelog.md
         echo "Generating list"
         gh release list
         echo "direct 4.4.8"
         gh release view 4.4.8
         echo "without writing"
         gh release list |cut -b1-6 |while read versiontag; do echo $versiontag; gh release view --json name,url,body "$versiontag" --jq '"# ["+.name+"]"+"("+.url+")",.body' |sed 's/^#/##/g'; done
         echo "writing"
         gh release list |cut -b1-6 |while read versiontag; do gh release view --json name,url,body "$versiontag" --jq '"# ["+.name+"]"+"("+.url+")",.body' |sed 's/^#/##/g'>> Changelog.md; done
         git add Changelog.md
         git commit -m "auto generated Changelog"
         echo "Pushing"
         git push
